name: Contracts CD

on:
  release:
    types:
      - created

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Cache wagmi ABI cache
        uses: actions/cache@v3
        with:
          path: ~/.wagmi-cli/plugins/cache
          key: ${{ runner.os }}-wagmi-cache-${{ hashFiles('**/wagmi.config.ts') }}

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build
        env:
          VITE_ETHERSCAN_API_KEY: ${{ secrets.VITE_ETHERSCAN_API_KEY }}

      - name: Run contract tests
        run: |
          cd packages/nouns-contracts
          pnpm test
