name: Subgraph CI

on:
  push:
    branches:
      - master
      - 'feature/*'
  pull_request:
    paths:
      - 'packages/nouns-contracts/abi/contracts/**'
      - 'packages/nouns-subgraph/**'
    branches:
      - '**'

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Yarn
        run: npm install -g yarn
      - run: yarn
      - run: yarn build
      - name: Prepare subgraph yaml
        run: |
          cd packages/nouns-subgraph
          yarn prepare:rinkeby
      - name: Generate code
        run: |
          cd packages/nouns-subgraph
          yarn codegen
      - name: Generate config
        run: |
          cd packages/nouns-subgraph
          yarn test:configgen
      - name: Run tests
        run: |
          cd packages/nouns-subgraph
          yarn test
      - name: Uninstall Yarn
        if: always()
        run: npm uninstall -g yarn
