name: Subgraph CI

on:
  push:
    branches:
      - master
      - 'feature/*'
  pull_request:
    paths:
      - 'packages/nouns-contracts/abi/contracts/**'
      - 'packages/nouns-subgraph/**'
    branches:
      - '**'

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build

      - name: Prepare subgraph yaml
        run: |
          cd packages/nouns-subgraph
          pnpm prepare:sepolia

      - name: Generate code
        run: |
          cd packages/nouns-subgraph
          pnpm codegen

      - name: Generate config
        run: |
          cd packages/nouns-subgraph
          pnpm test:configgen

      - name: Run tests
        run: |
          cd packages/nouns-subgraph
          pnpm test
